name: Generate Interop Report

on:
  workflow_dispatch:
  schedule:
    # update the integration suite once per week at Sunday 5am UTC
    - cron: '5 0 * * 0'

jobs:
  test-node:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: 'Get latest WHO Data'
        run: npm run fetch-who-int-svc
      - name: 'Clean certificates'
        run: rm -f ./certificates/*.json
      - name: 'Generate Latest Certificates'
        run: npm run generate-certificates
      - name: Run test with Node.js ${{ matrix.node-version }}
        run: npm run test-node
        continue-on-error: true
      - name: 'S3 Bucket sync'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: 'vaxcert-interop-reports'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # optional: defaults to us-east-1
          SOURCE_DIR: './reports'      # optional: defaults to entire repository
